# Generated by Django 5.2.4 on 2025-08-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busyschedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
