# Generated by Django 5.2.4 on 2025-08-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busyschedule', '0002_classschedule_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
